version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: poc
    container_name: poc-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - poc

  db:
    image: mysql:5.7
    container_name: poc-db
    env_file:
    - .env
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    expose:
      - ${DB_PORT}
    volumes:
      - './docker/mysql:/var/lib/mysql'
    networks:
      - poc
  nginx:
    image: nginx:alpine
    container_name: poc-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - poc

networks:
  poc:
    driver: bridge
